[package]
name = "embedded-cfu-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-io-async = "0.6.1"

defmt = { version = "0.3", optional = true }
log = { version = "0.4.14", optional = true }

[features]
default = []
defmt = [
    "dep:defmt",
]
log = [
    "dep:log",
]